start =
	expression

validchar =
	[0-9a-zA-Z_?!+\-=@#$%^&*/.><]

number = 
	p1:[1-9] p2:[0-9]*
		{return parseInt(p1 + p2.join(""));}

ws =
	[" "\t\n\r]*
		{return ""}

atom =  
        ws n:number ws
		{return n;}/
	ws c:validchar+ ws
		{return c.join("");}

expression =
	atom/
	"'" a:atom 
		{return ["quote", [a]]}/
	"'" e:expression
		{return ["quote", e]}/
	ws "(" e:expression* ")" ws
		{ return e;	}
